In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [4]:
col_names = ['pregnant','glucose','bp','skin','insuline','bmi','pedigree','age','label']

In [5]:
df = pd.read_csv("diabetes_dataset.csv",names=col_names)

In [6]:
df.head()

,pregnant,glucose,bp,skin,insuline,bmi,pedigree,age,label
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [7]:
df.tail()

    pregnant glucose  bp skin insuline   bmi pedigree age label
764       10     101  76   48      180  32.9    0.171  63     0
765        2     122  70   27        0  36.8     0.34  27     0
766        5     121  72   23      112  26.2    0.245  30     0
767        1     126  60    0        0  30.1    0.349  47     1
768        1      93  70   31        0  30.4    0.315  23     0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 769 entries, 0 to 768
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pregnant  769 non-null    object
 1   glucose   769 non-null    object
 2   bp        769 non-null    object
 3   skin      769 non-null    object
 4   insuline  769 non-null    object
 5   bmi       769 non-null    object
 6   pedigree  769 non-null    object
 7   age       769 non-null    object
 8   label     769 non-null    object
dtypes: object(9)
memory usage: 54.2+ KB

In [9]:
df['age'] = pd.to_numeric(df['age'],errors='coerce')

In [10]:
df.describe()

              age
count  768.000000
mean    33.240885
std     11.760232
min     21.000000
25%     24.000000
50%     29.000000
75%     41.000000
max     81.000000

In [1]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_encoded = df.apply(le.fit_transform)

NameError: name 'df' is not defined

In [ ]:
df_encoded.head()

In [ ]:
bins = [0,18,35,60,100]
labels = ['Child','Young','Adult','Senior']

df['Age Group'] = pd.cut(df['age'],bins=bins,labels=labels)

In [10]:
df.head()

,pregnant,glucose,bp,skin,insuline,bmi,pedigree,age,label,Age Group
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,NaN,Outcome,NaN
1,6,148,72,35,0,33.6,0.627,50.0,1,Adult
2,1,85,66,29,0,26.6,0.351,31.0,0,Young
3,8,183,64,0,0,23.3,0.672,32.0,1,Young
4,1,89,66,23,94,28.1,0.167,21.0,0,Young

In [ ]:
df['glucose'] = pd.to_numeric(df['glucose'],errors='coerce')
df['label'] = pd.to_numeric(df['label'],errors='coerce')
df = df.dropna(subset=['glucose','label'])
x=df[['glucose']]
y=df[['label']]

In [2]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

NameError: name 'train_test_split' is not defined

In [ ]:
model = LogisticRegression()
model.fit(x_train,y_train)

In [11]:
y_pred = model.predict(x_train)

In [ ]:
predicted_probs = model.predict_proba(x_train)[:,1]

In [ ]:
glucose_range = np.linspace(df['glucose'].min(),df['glucose'].max(),300).reshape(-1,1)
glucose_range_df = pd.DataFrame(glucose_range,columns=['glucose'])

In [ ]:
plt.figure(figsize=(8,5))
sns.scatterplot(x='glucose',y='label',color='blue',data=df,alpha=0.6,label='data')
plt.plot(glucose_range_df,predicted_probs,color='pink',linewidth=2,label='Logictic Regression')
plt.title("Logistic Regression Curve")
plt.xlabel("Glucose")
plt.ylabel("Label")
plt.grid(True)
plt.legend()
plt.show()

In [ ]:
df['Outcome'].value_counts()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
x=df[['Glucose']]
y=df['Outcome']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [ ]:
y_pred = model.predict(x_test)

y_pred_prob = model.predict_proba(x_test)

In [ ]:
x_train.shape
y_train.shape
x_test.shape
y_test.shape

In [ ]:
plt.figure(figsize=(7,10))
sns.scatterplot(x='Glucose',y='Outcome',color='blue',label='Data')
plt.plot()

In [ ]:
bins = [0,18,35,60,100]
labels = ['Child','Young','Adult','Senior']

df['Age Group'] = pd.cut(df['age'],bins=bins,labels=labels)

In [ ]:
df